// Generates the shipped ABI sources from the Foundry build in `out/`.
//
// Each entry below is resolved by its *source path*, not by artifact file
// name: `out/` is keyed on basename, so a `Verifier.sol` in `lib/` would
// otherwise be indistinguishable from ours. Every artifact's
// `metadata.settings.compilationTarget` is checked against the expected
// source path before its ABI is emitted.
//
// Output (all git-ignored, regenerated on every build):
//   src/abis/<Contract>.ts   — `as const` ABI, for viem/wagmi type inference
//   src/index.ts             — barrel of named `<contract>Abi` exports
//   json/<Contract>.json     — plain ABI array, for non-TS consumers
//
// `dist/` is wiped here too. tsc does not prune its own outDir, so a renamed or
// dropped contract would otherwise leave a stale module behind — and the `./*`
// subpath export would keep it importable and publishable.

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(pkgDir, "..", "..");
const outDir = join(repoRoot, "out");

/**
 * @type {Array<{ source: string, contract: string, export: string }>}
 * `source` is the path under the repo root; `contract` the name inside it;
 * `export` the camelCase symbol the package exposes.
 */
const CONTRACTS = [
    { source: "src/MASP.sol", contract: "MASP", export: "maspAbi" },
    { source: "src/AssetRegistry.sol", contract: "AssetRegistry", export: "assetRegistryAbi" },
    { source: "src/CommitmentTree.sol", contract: "CommitmentTree", export: "commitmentTreeAbi" },
    { source: "src/FeeConfig.sol", contract: "FeeConfig", export: "feeConfigAbi" },
    { source: "src/NullifierSet.sol", contract: "NullifierSet", export: "nullifierSetAbi" },
    { source: "src/swap/SwapWrapper.sol", contract: "SwapWrapper", export: "swapWrapperAbi" },
    { source: "src/swap/UniV3Adapter.sol", contract: "UniV3Adapter", export: "uniV3AdapterAbi" },
    { source: "src/swap/IMASPSwap.sol", contract: "IMASPSwap", export: "imaspSwapAbi" },
    { source: "src/swap/ISwapAdapter.sol", contract: "ISwapAdapter", export: "swapAdapterAbi" },
    { source: "src/interfaces/IVerifier.sol", contract: "IVerifier", export: "verifierInterfaceAbi" },
    { source: "src/interfaces/IWrappedNative.sol", contract: "IWrappedNative", export: "wrappedNativeAbi" },
    { source: "src/verifiers/Verifier.sol", contract: "Groth16Verifier", export: "groth16VerifierAbi" },
    {
        source: "src/verifiers/TreeUpdateBatchVerifier.sol",
        contract: "TreeUpdateBatchGroth16Verifier",
        export: "treeUpdateBatchVerifierAbi",
    },
];

function artifactPath({ source, contract }) {
    return join(outDir, source.split("/").pop(), `${contract}.json`);
}

function loadAbi(entry) {
    const path = artifactPath(entry);
    let artifact;
    try {
        artifact = JSON.parse(readFileSync(path, "utf8"));
    } catch (cause) {
        throw new Error(`missing artifact ${path} — run \`forge build\` first`, { cause });
    }
    const target = artifact.metadata?.settings?.compilationTarget ?? {};
    if (target[entry.source] !== entry.contract) {
        throw new Error(
            `${path} was compiled from ${JSON.stringify(target)}, expected ` +
                `{"${entry.source}":"${entry.contract}"} — basename collision with a lib/ or test/ contract`,
        );
    }
    if (!Array.isArray(artifact.abi)) throw new Error(`${path} has no abi array`);
    return { abi: artifact.abi, solc: artifact.metadata?.compiler?.version ?? "unknown" };
}

const srcDir = join(pkgDir, "src");
const abisDir = join(srcDir, "abis");
const jsonDir = join(pkgDir, "json");
const distDir = join(pkgDir, "dist");
for (const dir of [srcDir, jsonDir, distDir]) rmSync(dir, { recursive: true, force: true });
mkdirSync(abisDir, { recursive: true });
mkdirSync(jsonDir, { recursive: true });

const solcVersions = new Set();
const barrel = [
    "// GENERATED by scripts/generate.mjs from the Foundry build — do not edit.",
    "",
];

for (const entry of CONTRACTS) {
    const { abi, solc } = loadAbi(entry);
    solcVersions.add(solc);
    const body = [
        `// GENERATED from ${entry.source}:${entry.contract} (solc ${solc}) — do not edit.`,
        "",
        `export const ${entry.export} = ${JSON.stringify(abi, null, 4)} as const;`,
        "",
    ].join("\n");
    writeFileSync(join(abisDir, `${entry.contract}.ts`), body);
    writeFileSync(join(jsonDir, `${entry.contract}.json`), `${JSON.stringify(abi, null, 2)}\n`);
    barrel.push(`export { ${entry.export} } from "./abis/${entry.contract}.js";`);
}

barrel.push("");
writeFileSync(join(srcDir, "index.ts"), barrel.join("\n"));

console.log(
    `generated ${CONTRACTS.length} ABIs (solc ${[...solcVersions].join(", ")}) ` +
        `into packages/abi/{src,json}`,
);
